use_frameworks!

platform :ios, '9.0'

target 'OCHttpUtils_Example' do
  pod 'OCHttpUtils', :path => '../'
  pod  'Aspects'

  target 'OCHttpUtils_Tests' do
    inherit! :search_paths

    
  end
end
