# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc 'OCHttpUtils使用这个航道, 可以快速的对自己的私有库, 进行升级维护'
  lane :quickPodspec do |options|

  tagName = options[:tag]
  msg = options[:message]

  # 具体这个巷道上面执行哪些行为

  # 1. pod install
  # cocoapods(
  # clean: true,
  # podfile: "./Example/Podfile"
  # )

  # 2. git add .
  git_add(path: ".")
  #    git commit -m 'xxx'
  git_commit(path: ".", message: msg)
  #    git push origin master
  push_to_git_remote

  # 3. git tag 标签名称
  add_git_tag(
  tag: tagName
  )
  #    git push --tags
  push_git_tags

  # 4. pod spec lint
  pod_lib_lint(allow_warnings: true)
  #    pod repo push XXXX xxx.podspec
  pod_push(path: "OCHttpUtils.podspec", repo: "SeasonSpecs", allow_warnings: true)


  end
end
